2023-03-29 20:19:44,151 - __main__ - INFO - Testing for participant 2.
Programming starts in 2 process(es)
Traceback (most recent call last):
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/nibabel/loadsave.py", line 90, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '$/gpfs/gibbs/project/cmhn/data/face_scene/mask.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vast/palmer/home.grace/cmhn_ak2776/cmhn-s23-week09-fcma-ajkohl/09-fcma/./fcma_voxel_selection_cv.py", line 59, in <module>
    mask = io.load_boolean_mask(mask_file)
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/brainiak/io.py", line 126, in load_boolean_mask
    data = nib.load(path).get_data()
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/nibabel/loadsave.py", line 92, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '$/gpfs/gibbs/project/cmhn/data/face_scene/mask.nii.gz'
Traceback (most recent call last):
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/nibabel/loadsave.py", line 90, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '$/gpfs/gibbs/project/cmhn/data/face_scene/mask.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vast/palmer/home.grace/cmhn_ak2776/cmhn-s23-week09-fcma-ajkohl/09-fcma/./fcma_voxel_selection_cv.py", line 59, in <module>
    mask = io.load_boolean_mask(mask_file)
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/brainiak/io.py", line 126, in load_boolean_mask
    data = nib.load(path).get_data()
  File "/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/nibabel/loadsave.py", line 92, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '$/gpfs/gibbs/project/cmhn/data/face_scene/mask.nii.gz'
srun: error: p08r06n07: tasks 0-1: Exited with exit code 1
